<?php
/**
 * @file
 * This module is flash dynamic menu module for Drupal 6.
 *
 * Written by Webdorado team.
 */

/**
 * Implements hook_help().
 */
function folder_menu_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#folder_menu":
      $output = '<p>' . t("Download 'jscolor' library from <a href='http://jscolor.com/release/jscolor-1.4.0.zip'>http://jscolor.com/release/jscolor-1.4.0.zip</a> and extract it to sites/all/libraries/jscolor directory.<br />
      Download 'AC_FL_RunContent' from <a href='http://allencrosticrealty.com/AC-RunActiveContent.js/at_download/file'>http://allencrosticrealty.com/AC-RunActiveContent.js/at_download/file</a> library and copy AC_RunActiveContent.js file to sites/all/libraries/AC_FL_RunContent directory.<br />
      You can change Folder Menu settings on <strong>Administer > Site configuration > Folder Menu settings ('admin/settings/folder_menu')</strong>.<br />
      Then you must select Folder Menu block Region on <strong>Administer > Site configuration > Blocks menu ('admin/build/block')</strong>.<br /><br />
      To show more than three menus and five submenus, go to Folder Menu module page on <a href='drupal.org'>Drupal.org</a>.") . '</p>';
      break;
  }
  return $output;
}

/**
 * Implements hook_perm().
 */
function folder_menu_perm() {
  return array('access folder_menu administration');
}

/**
 * Implements hook_menu().
 */
function folder_menu_menu() {
  $items = array();

  $items['admin/settings/folder_menu'] = array(
    'title' => 'Folder Menu settings',
    'description' => 'Description of your folder_menu settings page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('folder_menu_admin'),
    'access arguments' => array('access folder_menu administration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Menu loader callback. Load a Folder Menu settings.
 */
function folder_menu_admin() {
  $path = 'sites/all/libraries/jscolor';
  drupal_add_js($path . '/jscolor.js');
  $form = array();
  if (!file_exists("sites/all/libraries/AC_FL_RunContent/AC_RunActiveContent.js") || !file_exists("sites/all/libraries/jscolor/jscolor.js")) {
     drupal_set_message(t("Download 'jscolor' library from <a href='http://jscolor.com/release/jscolor-1.4.0.zip'>http://jscolor.com/release/jscolor-1.4.0.zip</a> and extract it to sites/all/libraries/jscolor directory.<br />
      Download 'AC_FL_RunContent' from <a href='http://allencrosticrealty.com/AC-RunActiveContent.js/at_download/file'>http://allencrosticrealty.com/AC-RunActiveContent.js/at_download/file</a> library and copy AC_RunActiveContent.js file to sites/all/libraries/AC_FL_RunContent directory.<br />"), 'error');
  }

  $menus = menu_get_menus();
  unset($menus['navigation']);

  $form['folder_menu_parent'] = array(
    '#type' => 'select',
    '#title' => t('Menu Parent'),
    '#description' => t('The menu parent from which to show a Folder menu.'),
    '#default_value' => variable_get('folder_menu_parent', 'primary-links'),
    '#options' => $menus,
  );
  $menu_type = variable_get('folder_menu_parent', 'primary-links');
  $menus = menu_tree_all_data($menu_type);
  $i = 0;
  foreach ($menus as $menu) {
    if ($menu['below']) {
      $i += count($menu['below']);
	}
  }
  if ($i > 5) {
    drupal_set_message(t('To show more than five submenus, go to Folder Menu module page on <a href="http://drupal.org">Drupal.org</a>.'), 'warning', FALSE);
  }
  if (count($menus) > 3) {
    drupal_set_message(t('To show more than three menus, go to Folder Menu module page on <a href="http://drupal.org">Drupal.org</a>.'), 'warning', FALSE);
  }
  $form['folder_menu_position'] = array(
    '#type' => 'select',
    '#title' => t('Menu Position'),
    '#description' => t('Position can be absolute or fixed'),
    '#default_value' => variable_get('folder_menu_position', 'fixed'),
    '#options' => array('fixed' => t('Fixed'), 'absolute' => t('Absolute')),
  );

  $form['folder_menu_distance_from_top'] = array(
    '#type' => 'textfield',
    '#title' => t('Distance from top'),
    '#default_value' => variable_get('folder_menu_distance_from_top', '0'),
    '#size' => 21,
    '#description' => t('Distance from top of the page. (px)'),
  );

  $options_font = array(
    'Verdana' => 'Verdana',
    'Lucida' => 'Lucida',
    'Georgia' => 'Georgia');

  $form['folder_menu_font'] = array(
    '#type' => 'select',
    '#title' => t('Menu Font'),
    '#options' => $options_font,
    '#default_value' => variable_get('folder_menu_font', 'Georgia'),
  );

  $form['folder_menu_background_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Menu Background Color'),
    '#default_value' => variable_get('folder_menu_background_color', 'F2F2F2'),
    '#attributes' => array('class' => 'color'),
    '#size' => 21,
  );

  $form['folder_menu_text_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Menu Text Color'),
    '#default_value' => variable_get('folder_menu_text_color', '525A66'),
    '#attributes' => array('class' => 'color'),
    '#size' => 21,
  );

  $form['folder_menu_hover_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Menu Hover Color'),
    '#default_value' => variable_get('folder_menu_hover_color', '7FBFFF'),
    '#attributes' => array('class' => 'color'),
    '#size' => 21,
  );

  $form['folder_menu_submenu_text_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Submenu Text Color'),
    '#default_value' => variable_get('folder_menu_submenu_text_color', '525A66'),
    '#attributes' => array('class' => 'color'),
    '#size' => 21,
  );

  $form['folder_menu_submenu_hover_color'] = array(
    '#type' => 'textfield',
    '#title' => t('Submenu Hover Color'),
    '#default_value' => variable_get('folder_menu_submenu_hover_color', '7FBFFF'),
    '#attributes' => array('class' => 'color'),
    '#size' => 21,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_block().
 */
function folder_menu_block($op='list', $delta=0) {

  $menuxmlurl = drupal_get_path('module', 'folder_menu') . '/menu.php';

  switch (variable_get('folder_menu_font', 'Georgia')) {
    case 'Georgia':
      $swfurl = drupal_get_path('module', 'folder_menu') . '/VerticalGeorgia';
      break;

    case 'Lucida':
      $swfurl = drupal_get_path('module', 'folder_menu') . '/VerticalLucida';
      break;

    case 'Verdana':
      $swfurl = drupal_get_path('module', 'folder_menu') . '/VerticalVerdana';
      break;
  }

  if ($op == "list") {
    $block = array();
    $block[0]["info"] = 'Folder Menu';
    $block[0]["content"] = '';
    return $block;
  }
  elseif ($op == 'view') {
    switch ($delta) {
      case 0:
        $block_content = '';
        $block['subject'] = '';
        $block['content'] = folder_menu_createFlashDiv($swfurl, $menuxmlurl);
        break;
    }
    return $block;
  }
}

/**
 * Function folder_menu_createFlashDiv().
 */
function folder_menu_createFlashDiv($swfurl, $menuxmlurl) {
  $path = 'sites/all/libraries/AC_FL_RunContent';
  drupal_add_js($path . '/AC_RunActiveContent.js');
  drupal_add_js(drupal_get_path('module', 'folder_menu') . '/js/folder_menu_functions.js');
  return '
  <div id="foldermenuverticalContainer" onmouseover="folder_menu_onmouseover_vertical();" onmouseout="folder_menu_onmouseout_vertical();" style="position:fixed; left:0px; top:' . variable_get('folder_menu_distance_from_top', '0') . 'px; overflow:hidden; width:50px; height:1500px; z-index:10000; position:' . variable_get('folder_menu_position', 'fixed') . '">

  <script language="javascript">

  if (typeof(AC_FL_RunContent)!="undefined") {
AC_FL_RunContent(
"codebase", "http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=9,0,0,0",
"width", "1000",
"height", "3000",
"src", "' . $swfurl . '",
"quality", "high",
"pluginspage", "http://www.macromedia.com/go/getflashplayer",
"align", "left",
"play", "true",
"loop", "true",
"scale", "showall",
"wmode", "transparent",
"devicefont", "false",
"id", "FolderMenuVerticalElem",
"name", "FolderMenuVerticalElem",
"menu", "true",
"allowFullScreen", "false",
"allowScriptAccess","always",
"movie", "' . $swfurl . '",
"salign", "t",
"flashvars", "xmlUrl=' . $menuxmlurl . '"
);

if(typeof(FolderMenuVerticalElem)=="undefined")
folder_menu_initFlash_Moz_vertical();
else
initFlash_vertical();
}

function folder_menu_onmouseover_vertical() {
if(typeof(FolderMenuVerticalObj)!="undefined")	{
FolderMenuVerticalObj.TOtrigger=true;
FolderMenuVerticalObj.setHeightAndWidthTO();
}
}

function folder_menu_onmouseout_vertical() {
if(typeof(FolderMenuVerticalObj)!="undefined")	{
FolderMenuVerticalObj.TOtrigger=false;
}
}

function folder_menu_initFlash_Moz_vertical() {
if(typeof(document.FolderMenuVerticalElem.getWidth)=="function")
FolderMenuVerticalObj=new FolderMenuVertical("foldermenuverticalContainer",document.FolderMenuVerticalElem,"FolderMenuVerticalObj", initFlash_Moz_vertical);
else {setTimeout("folder_menu_initFlash_Moz_vertical()",500);}
}

function initFlash_vertical()	{
if(typeof(FolderMenuVerticalElem.getWidth)=="function")
FolderMenuVerticalObj=new FolderMenuVertical("foldermenuverticalContainer",FolderMenuVerticalElem,"FolderMenuVerticalObj", initFlash_vertical);
else {setTimeout("initFlash_vertical()",500);}
}
</script>
</div>
<script language="javascript">
var foldermenuverticalContainerDiv = document.getElementById("foldermenuverticalContainer");
document.body.appendChild(foldermenuverticalContainerDiv);
</script>';
}
